<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Replied.FollowUser.Application\Replied.FollowUser.Application.csproj" />
    <ProjectReference Include="..\Replied.FollowUser.Infrastructure.InMemory\Replied.FollowUser.Infrastructure.InMemory.csproj" />
  </ItemGroup>

</Project>
